# .github/workflows/refresh-github-data.yml
name: Refresh GitHub Profile Data

on:
  schedule:
    - cron: '0 13 * * 1'   # Mondays 13:00 UTC
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: refresh-github-data
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (optional)
        run: |
          if [ -f package-lock.json ]; then npm ci; fi

      - name: Fetch GitHub data
        run: node scripts/fetch_github.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          if git diff --quiet src/data/github.json; then
            echo "No changes."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add src/data/github.json
            git commit -m "chore: refresh GitHub data $(date -u +%FT%TZ)"
            git push
          fi
